[package]
name = "rust_cms"
version = "0.1.0"
edition = "2021"

[dependencies]
bevy_reflect = "0.9.0"
rocket = "0.5.0-rc.2"
rocket_auth = "0.4.0"
rocket_dyn_templates = { version = "0.1.0-rc.2", features = ["tera"] }
